---
# security_lab_setup.yml
# Purpose: Creates isolated environment for studying CVE-2023-22809
# WARNING: Only for use in authorized educational environments
# Ensure proper isolation and authorization before use

- name: Setup CVE-2023-22809 Study Environment
  hosts: all
  become: yes
  vars:
    test_user: editonly
    test_password: editonly
    sudo_version: "1.9.12p1"
    
  tasks:
    - name: Create test user with password
      shell: |
        useradd -m -s /bin/bash {{ test_user }}
        echo "{{ test_user }}:{{ test_password }}" | chpasswd
        
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install required packages
      apt:
        name: 
          - g++
          - gcc
          - make
        state: present
        install_recommends: no
      environment:
        DEBIAN_FRONTEND: noninteractive
        
    - name: Copy exploit test script
      copy:
        src: ./data/exploit.py
        dest: "/home/{{ test_user }}/exploit.py"
        owner: "{{ test_user }}"
        mode: '0744'
        
    - name: Copy sudo source
      copy:
        src: "./data/sudo-{{ sudo_version }}.tar.gz"
        dest: "/root/sudo-{{ sudo_version }}.tar.gz"
        
    - name: Extract sudo source
      unarchive:
        src: "/root/sudo-{{ sudo_version }}.tar.gz"
        dest: /root/
        remote_src: yes
        
    - name: Configure sudo
      command: ./configure
      args:
        chdir: "/root/sudo-{{ sudo_version }}"
        
    - name: Build sudo
      command: make
      args:
        chdir: "/root/sudo-{{ sudo_version }}"
        
    - name: Install sudo
      command: make install
      args:
        chdir: "/root/sudo-{{ sudo_version }}"
        
    - name: Refresh shell hash table
      shell: hash -r
        
    - name: Create test file
      file:
        path: /etc/writable
        state: touch
        mode: '0644'
        
    - name: Configure sudoers entry
      lineinfile:
        path: /etc/sudoers
        line: "{{ test_user }} ALL=(ALL:ALL) sudoedit /etc/writable"
        validate: 'visudo -cf %s'
