---
- name: Setup vulnerable environment for CVE-2019-14287
  hosts: all
  become: yes
  vars:
    hackeruser: hacker
    hackerpass: password123
    sudo_version: "1.8.27"  

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install build dependencies
      apt:
        pkg:
          - build-essential
          - make
          - gcc

    - name: Copy sudo source
      copy:
        src: "./data/sudo-{{ sudo_version }}.tar.gz"
        dest: "/home/sudo-{{ sudo_version }}.tar.gz"

    - name: Extract sudo source
      unarchive:
        src: "/home/sudo-1.8.27.tar.gz"
        dest: /home/
        remote_src: yes

    - name: Configure sudo
      command: sudo ./configure
      args:
        chdir: "/home/sudo-{{ sudo_version }}"

    - name: Build sudo
      command: sudo make
      args:
        chdir: "/home/sudo-{{ sudo_version }}"

    - name: Comment out @includedir in sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^@includedir /etc/sudoers.d'
        line: '#includedir /etc/sudoers.d'
        state: present
        validate: 'visudo -cf %s'
      become: yes

    - name: Install sudo
      command: sudo make install
      args:
        chdir: "/home/sudo-{{ sudo_version }}"

    - name: Create test user with password
      shell: |
        useradd -m -s /bin/bash {{ hackeruser }}
        echo "{{ hackeruser }}:{{ hackerpass }}" | chpasswd

    - name: Configure sudoers with exploit permissions
      lineinfile:
        path: /etc/sudoers
        line: 'hacker ALL=(ALL,!root) NOPASSWD: /bin/bash, /usr/bin/python3'
        validate: 'visudo -cf %s'

    - name: Allow hacker to use sudo without TTY
      lineinfile:
        path: /etc/sudoers
        line: 'Defaults:ALL !requiretty'
        validate: 'visudo -cf %s'

    - name: Verify new sudo installation
      ansible.builtin.command:
        cmd: /usr/local/bin/sudo --version
      become: yes
      register: sudo_version

    - name: Print the new sudo version
      ansible.builtin.debug:
        msg: "New sudo version installed: {{ sudo_version.stdout }}"

    - name: Copy exploit script to hacker's home
      copy:
        src: "./data/sudo_exploit.py"
        dest: "/home/hacker/sudo_exploit.py"
        mode: "0755"
        owner: hacker
