---
- name: Set up attack environment
  hosts: ubuntu2
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - curl
        state: present

    - name: Install Python requirements
      pip:
        name:
          - requests
          - urllib3
        state: present

    - name: Create exploit directory
      file:
        path: /opt/exploit
        state: directory
        mode: '0755'

    - name: Copy exploit script
      copy:
        src: data/exploit.py
        dest: /opt/exploit/exploit.py
        mode: '0755'
