---
- name: Install ThinkPHP Server vulnerable to RCE (CVE-2018-20062)
  hosts: ubuntu1
  become: yes
  vars:
    thinkphp_version: "5.0.23"
    source_zip: "think-{{thinkphp_version}}.zip"
    root_dir: "/var/www/html"

  tasks:
    - name: Add PHP PPA repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - unzip
        - apache2
        - php7.3
        - libapache2-mod-php7.3

    - name: Copy ThinkPHP zip to /tmp/
      copy:
        src: "./data/{{ source_zip }}"
        dest: "/tmp/{{ source_zip }}"

    - name: Extract ThinkPHP to apache root directory
      unarchive:
        src: "/tmp/{{ source_zip }}"
        dest: "{{ root_dir }}"
        remote_src: yes
    
    - name: Set permissions for /var/www/html
      file:
        path: /var/www/html
        state: directory
        mode: '0777'
        recurse: yes
