blueprint: ubuntu2204
ubuntu:
  playbook: ubuntu.yml
  command:
    - "git config --global --add safe.directory /home/ubuntu/rce-via-tagname"
    - "ls /home/ubuntu/rce-via-tagname/"
    - "python3 /home/ubuntu/rce-via-tagname/exploit.py"
    - "ls /home/ubuntu/rce-via-tagname/"