- name: Ubuntu machine to recreate CVE-2021-34081 (File create/overwrite vulnerability with gitsome)
  hosts: all
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Node.js and npm
      ansible.builtin.apt:
        pkg:
          - nodejs
          - npm
        state: present

    - name: Install Git
      ansible.builtin.apt:
        pkg:
          - git
        state: present

    - name: Create /home/ubuntu
      file:
        path: /home/ubuntu
        state: directory
        mode: '0777'

    - name: Copy vulnerable gitsome version
      ansible.builtin.copy:
        src: ./data/gitsome-0.2.3.tgz
        dest: /home/ubuntu/gitsome-0.2.3.tgz
        mode: '0777'

    - name: Install vulnerable gitsome with npm
      npm:
        name: /home/ubuntu/gitsome-0.2.3.tgz
        path: /home/ubuntu/
        state: present

    - name: Copy compressed Git repository to VM
      ansible.builtin.copy:
        src: ./data/rce-via-tagname.tar.gz
        dest: /home/ubuntu/rce-via-tagname.tar.gz

    - name: Extract the repository
      ansible.builtin.unarchive:
        src: /home/ubuntu/rce-via-tagname.tar.gz
        dest: /home/ubuntu/
        remote_src: yes

    - name: Set permissions to 777 for the repository
      ansible.builtin.file:
        path: /home/ubuntu/rce-via-tagname
        mode: '0777'
        recurse: yes

    - name: Copy poc.js into the cloned repository
      ansible.builtin.copy:
        src: ./data/poc.js
        dest: /home/ubuntu/rce-via-tagname/poc.js
        mode: '0777'

    - name: Copy exploit.py into the cloned repository
      ansible.builtin.copy:
        src: ./data/exploit.py
        dest: /home/ubuntu/rce-via-tagname/exploit.py
        mode: '0777'