blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  trace: nginx
  playbook: ubuntu1.yml
ubuntu2:
  trace: "python3"
  playbook: ubuntu2.yml
  command:
    - "python3 /opt/exploit/exploit.py -u http://%ubuntu1%:8080"