- name: Install Apache Tomcat vulnerable to JSP File（CVE-2017-12617）
  hosts: all
  become: yes
  tasks:
    - name: Create data directory
      file:
        path: /home/vagrant/data
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'
      
    - name: Install Java and Dependencies
      apt:
        name: 
          - default-jdk
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Python Requests Library
      pip:
        name: requests
        state: present

    - name: Extract Tomcat
      unarchive:
        src: ./data/apache-tomcat-9.0.0.M1.tar.gz
        dest: /home/vagrant/

    - name: Ensure Tomcat startup script is executable
      file:
        path: /home/vagrant/apache-tomcat-9.0.0.M1/bin/startup.sh
        mode: '+x'

    - name: Copy Exploit Script
      copy:
        src: data/exploit.py
        dest: /home/vagrant/data/exploit.py
        mode: '+x'

    - name: Change Tomcat Directory Ownership
      file:
        path: /home/vagrant/apache-tomcat-9.0.0.M1
        owner: vagrant
        group: vagrant
        recurse: yes

    - name: Set Tomcat Directory Permissions
      file:
        path: /home/vagrant/apache-tomcat-9.0.0.M1
        mode: '0755'
        recurse: yes

    - name: Modify Web XML Configuration
      lineinfile:
        path: /home/vagrant/apache-tomcat-9.0.0.M1/conf/web.xml
        regexp: '<param-name>listings</param-name>'
        line: '   <param-name>readonly</param-name>'
        backup: yes

    - name: Verify Web XML Configuration Change
      command: grep -A 5 -B 5 readonly /home/vagrant/apache-tomcat-9.0.0.M1/conf/web.xml

    - name: Start Tomcat
      command: ./startup.sh
      args:
        chdir: /home/vagrant/apache-tomcat-9.0.0.M1/bin
      async: 60
      poll: 0

    - name: Wait for Tomcat to Start
      pause:
        seconds: 10

    - name: Set Exploit Script Permissions
      file:
        path: /home/vagrant/data/exploit.py
        mode: '0755'

    - name: Set Data Directory Permissions
      file:
        path: /home/vagrant/data
        mode: '0755'
        recurse: yes
